### ISSUE TITLE
AMD Ryzen 7 3700x

### ISSUE THREAD

**Issue by paulomcnally** [CarlosCarrera/opencore-catalina#1]
Work for AMD Ryzen 7 3700x?

**Comment by paulomcnally** [comment]
And GPU Radeon RX 5600 XT?

**Comment by paulomcnally** [comment]
Yes! Work!

**Comment by CarlosCarrera** [comment]
Hi, even if it works, I would strongly suggest doing your own EFI folder by following the guide here: https://dortania.github.io/OpenCore-Install-Guide/
