### ISSUE TITLE
USB Map?

### ISSUE THREAD

**Issue by dmarkey** [CarlosCarrera/opencore-catalina#2]
Hi there,

Thanks for this first of all, got my hackintosh up and running in minutes.

You have any luck with a USB map which is probably causing sleep/wake to fail?

**Comment by CarlosCarrera** [comment]
I haven't done USB map in this build yet, it will probably fix sleep/wake issues. 
Anyways, this repo is not intended to clone and use it straight away in other hackintoshes. I would highly recommend using the Dortania guide: https://dortania.github.io/OpenCore-Install-Guide/

**Comment by dmarkey** [comment]
Yeah I have a the same Mobo so it just worked :) Thanks
